provider/pkg/gen/schema.go

If there is a collision between parent properties and flattened properties, the resulting metadata is non-deterministic. This enforces an ordering but does so arbitrarily. Not sure how we want to handle this - we could introduce an `sdkName` equivalent to distinguish them. We should discuss solving that in a separate ticket: https://github.com/pulumi/pulumi-gcp-native/issues/31

Deterministic output for flattened properties

---

examples/examples_nodejs_test.go
examples/examples_test.go
examples/functions-ts/Pulumi.yaml
examples/functions-ts/index.ts
examples/functions-ts/package.json
examples/functions-ts/pythonfunc/main.py
examples/functions-ts/tsconfig.json
provider/pkg/provider/provider.go
provider/pkg/resources/resources.go

Also, fixes the DELETE for storage bucket/object

Add a Cloud Function example

---

provider/cmd/pulumi-resource-gcp-native/metadata.json
provider/pkg/gen/schema.go
provider/pkg/provider/provider.go

I went through the list of resources that we mark as "NoDelete" and found only one case of a different naming: `dropDatabase` for Spanner (added an exception). There are also some "cancel", "disable", etc. methods that we may want to invoke as deletes - but they are all single cases without any apparent rule.
I found that the classic GCP provider already has 10 resources that are only deleted from the state but not from GCP - so I went ahead and added a warning of this kind to the code. We can refine this later after the initial preview.
Finally, I added a special case for IamPolicy resources: invoke an update with an empty body. IamPolicy resources have awkward IDs ending with `:getIamPolicy`. I coded around this in the provider code for now, let's see if there are any other resources …

Delete for non-deletable resources

---

CHANGELOG.md
provider/pkg/provider/provider.go

Removes a hack that is leftover from pre-metadata code. We don't need to remove ID parameters from the body anymore, as we have the full list of body parameters in the metadata.
It's a bit hard to create a test for DNS resources but I verified manually that the name is now being sent.
Fix https://github.com/pulumi/pulumi-google-native/issues/61

Populate body parameter even if its name matches a url parameter

---

CHANGELOG.md
provider/pkg/provider/diff.go
provider/pkg/provider/diff_test.go
provider/pkg/provider/provider.go

Our special `__inputs` property is the basis for diff calculation, so we should refresh it when `Read()` method is invoked. The implementation is copied from Azure-Native and AWS-Native modulo `getInputsFromState` which is specific for each provider metadata.
Fix https://github.com/pulumi/pulumi-google-native/issues/65

Recalculate __inputs during refresh

---

provider/pkg/gen/schema.go
provider/pkg/provider/provider.go
provider/pkg/resources/convert.go
provider/pkg/resources/convert_test.go
provider/pkg/resources/resources.go

I extended metadata to keep information about named types, maps, and arrays in addition to resource metadata that we have today. This is needed for the follow-up PR that tracks [fingerprint](https://github.com/pulumi/pulumi-google-native/issues/126) properties in the metadata. I expect we'll get more use cases in the future - basically every time the shape of SDK needs to differ from the wire format.
This is a technical change that shouldn't affect end users. The code is largely copied from azure-native.

Store metadata for all types

---

provider/pkg/gen/discovery.go

Resolve https://github.com/pulumi/pulumi-google-native/issues/84
We don't want to warn on those - most of the resources aren't of interest for us for now.

Remove a warning if no create method is found

---

CHANGELOG.md
provider/pkg/resources/convert.go
provider/pkg/resources/convert_test.go

Fix the panic in https://github.com/pulumi/pulumi-google-native/issues/160
It doesn't really fix the scenario though because the next error I get is 
```
error sending request: googleapi: Error 400: Invalid value for field 'resource': 
'{  "name": "bla-4a6a8c1",  "description": "Edge Security Policy",  "rule": [{    
"priority": 1000,  ...'. Rules cannot be updated with patch, please use addRule, 
removeRule, or patchRule instead., invalid: "https://www.googleapis.com/compute/beta/projects/pulumi-development/global/securityPolicies/bla-4a6a8c1" 
map[description:Edge Security Policy fingerprint:CSn77VRIOVI= labelFingerprint:42WmSpB8rSM= name:bla-4a6a8c1 rules:[map[action:allow match:map[config:map[srcIpRanges:[0.0.0.0 1.1.1.1]] versionedExpr:SRC_IPS_V1] priority:1000] map[action:deny(403) …
```

Fix a panic when an array property is updated to a larger number of elements

---

CHANGELOG.md
provider/pkg/provider/provider.go

Support initialization failures by checkpointing partially created resources into the state.
Fix https://github.com/pulumi/pulumi-google-native/issues/149

Support initialization failures

---

examples/gke-ts/index.ts

CI tests already set `google-native:region` and `google-native:project`,
so it's not necessary to set those values explicitly.

Simplify config setting for GKE example

---

Makefile

A [recent change](https://github.com/pulumi/pulumi/pull/7479) to the codegen has changed the way `setup.py` is emitted that requires an update to the `Makefile` to set the version.
I also noticed both the `VERSION` and `PLUGIN_VERSION` were being set to the Python-style version. Not sure if that was intentional (unlikely), so I've fixed it up so these get the correct version styles.

Fix Makefile to set Python SDK version

---

CHANGELOG.md
provider/pkg/provider/provider.go

Improves the logic for replacement detection. Use cases that I tested it with:
- A new property is added to the resource definition that should cause a replacement
- A property is deleted from the resource definition that should cause a replacement
- A property SDK name doesn't match its API name
- A property that is a part of a resource ID is changed (a URL parameter)
It also touched the default value calculation for the last use case above. Fix #170

Improve replacement detection

---

examples/gke-ts/index.ts
provider/pkg/googleclient/http.go

Fix #234 (well, rather work around it with a temporary measure)
It turns out that the build failure was caused by CI updating to Go 1.16.10 (from 1.16.9) which shipped a breaking bug https://github.com/golang/go/issues/49366 That bug makes `httputil.DumpResponse` fail for HTTP/2 responses.
In the spirit of the simplest possible fix of P1, I've disabled dumping the response for now. It looks like they want to backport the fix to 1.16.11 - so we can probably wait for that one to release. Tracked in https://github.com/golang/go/issues/49558

Disable response body dump

---

CHANGELOG.md
provider/pkg/provider/provider.go

It is semantically wrong to statically populate the `Replaces` property of a Diff response with all the properties that require replacement for a given resource type. This PR removes this, which means we will detect _no_ replacements. I think this is a better type of error than unneeded replacements. 
Similar to https://github.com/pulumi/pulumi-aws-native/pull/205
Fix #185
Fix #217
Fix #232
Fix #243

Disable unconditional replaces

---

Makefile
README.md
sdk/python/README.md

Closes #250 
- Point to native guide rather than classic.
- Tidy up code blocks.

Fix link to guide

---

.github/workflows/weekly-pulumi-update.yml

Automation hook that would open PR in native providers on every pulumi/pulumi release. For starters, it runs every week (on Thursday - I think we release pulumi on Wed), pulls the latest Go mod and opens a PR if there is any change.
Sample run: https://github.com/pulumi/pulumi-google-native/runs/4593367718?check_suite_focus=true
Sample PR: https://github.com/pulumi/pulumi-google-native/pull/262
If accepted, I'll add the same file to all other native providers.

Workflow to update pulumi/pulumi automatically

---

CHANGELOG.md
Makefile
provider/pkg/gen/schema.go
provider/pkg/gen/utilities.go
provider/pkg/gen/utilities_test.go
sdk/dotnet/CloudResourceManager/V1/GetProject.cs
sdk/dotnet/CloudResourceManager/V1/Project.cs
sdk/dotnet/CloudResourceManager/V1Beta1/GetProject.cs
sdk/dotnet/CloudResourceManager/V1Beta1/Project.cs
sdk/dotnet/CloudResourceManager/V3/GetProject.cs
sdk/dotnet/CloudResourceManager/V3/Project.cs
sdk/go/google/cloudresourcemanager/v1/getProject.go
sdk/go/google/cloudresourcemanager/v1/project.go
sdk/go/google/cloudresourcemanager/v1beta1/getProject.go
sdk/go/google/cloudresourcemanager/v1beta1/project.go
sdk/go/google/cloudresourcemanager/v3/getProject.go
sdk/go/google/cloudresourcemanager/v3/project.go
sdk/nodejs/cloudresourcemanager/v1/getProject.ts
sdk/nodejs/cloudresourcemanager/v1/project.ts
sdk/nodejs/cloudresourcemanager/v1beta1/getProject.ts
sdk/nodejs/cloudresourcemanager/v1beta1/project.ts
sdk/nodejs/cloudresourcemanager/v3/getProject.ts
sdk/nodejs/cloudresourcemanager/v3/project.ts
sdk/python/pulumi_google_native/cloudresourcemanager/v1/get_project.py
sdk/python/pulumi_google_native/cloudresourcemanager/v1/project.py
sdk/python/pulumi_google_native/cloudresourcemanager/v1beta1/get_project.py
sdk/python/pulumi_google_native/cloudresourcemanager/v1beta1/project.py
sdk/python/pulumi_google_native/cloudresourcemanager/v3/get_project.py
sdk/python/pulumi_google_native/cloudresourcemanager/v3/project.py

Fixes #277 
We replace projectId with project elsewhere because we then build the full projectId dynamically within the provider. However the projectId within the actual Project resource type does not need auto-naming.
Not  committing the test example as it seems to take some time to actually delete the project which could cause issues in CI/CD.

Fix naming of projectId property on the Project resource

---

Makefile

The `tsc` command on line 52 would always use a globally installed TypeScript, regardless of the one installed by yarn on the previous line.
Replaces #297 to run tests

Use TypeScript package from Yarn, not global

---

examples/gke-ts/index.ts
provider/cmd/pulumi-gen-google-native/main.go
provider/cmd/pulumi-resource-google-native/main.go
provider/pkg/gen/compression.go
provider/pkg/gen/discovery.go
provider/pkg/gen/overrides.go
provider/pkg/gen/schema.go
provider/pkg/gen/utilities.go
provider/pkg/gen/utilities_test.go
provider/pkg/googleclient/credentials.go
provider/pkg/googleclient/http.go
provider/pkg/googleclient/http_test.go
provider/pkg/googleclient/mockTokenSource_test.go
provider/pkg/provider/diff.go
provider/pkg/provider/diff_test.go
provider/pkg/provider/ids.go
provider/pkg/provider/ids_test.go
provider/pkg/provider/log.go
provider/pkg/provider/provider.go
provider/pkg/provider/serve.go
provider/pkg/resources/convert.go
provider/pkg/resources/convert_test.go
provider/pkg/resources/resources.go
provider/pkg/version/version.go

This change refactors the resource metadata used by the provider to perform resource operations. The previous layout assumed that certain REST operations worked the same across the SDK, while the new layout explicitly includes information for every CRUD operation.

Refactor metadata

---

CHANGELOG.md
provider/pkg/gen/discovery.go
provider/pkg/gen/schema.go
provider/pkg/provider/ids.go
provider/pkg/provider/ids_test.go
provider/pkg/provider/provider.go
provider/pkg/resources/resources.go
provider/pkg/resources/resources_test.go

Previously, the provider computed a resource ID during the Create operation, and then used this ID with hardcoded HTTP verbs for Read, Update, and Delete operations. While this works for many resources, some don’t follow this pattern. This change refactors the provider logic to use the endpoints and HTTP verbs specified for each operation by the schema.
---
I computed a [metadata diff](https://gist.github.com/lblackstone/52f66a0e9e9c4e819d999e9f3a0c1f8e) compared to the `v0.15.0` release. There are a bunch of changes to resources with a `IamPolicy` suffix that change `get` to `set` on update methods. The old metadata was not accurate for these cases, and the provider [previously handled them with an override](https://github.com/pulumi/pulumi-google-native/blob/v0.15.0/provider/pkg/provider …

Use schema information for all REST operations

---

provider/pkg/provider/provider.go

Prior to 096d781, the provider metadata did not map setIamPolicy methods correctly for resource Updates, so they were updated during a resource Update. The metadata has been corrected, so the manual substitution is no longer required.

Drop obsolete substitution logic from provider Update

---

CHANGELOG.md
provider/pkg/googleclient/http.go
provider/pkg/provider/overrides.go
provider/pkg/provider/provider.go

Previously, the provider always mapped resource operations 1:1 with a REST API call. While this works for many cases, some operations are more complex, and require special handling. This change adds lookup tables of functions for each type of operation. If a function is present for a particular resource, this function will be executed by the provider instead of using the default REST logic.

Check for override functions on resource delete

---

CHANGELOG.md
provider/pkg/gen/compression.go

The io.CopyN function only copies up to N bytes, so this was failing for long schema elements. Reverted the change and disabled the lint check for this line.

Fix regression in schema decompressor

---

.github/workflows/pull_request.yml

The environment variable needed for this step is not available across jobs, and while we could change that I think it also makes sense to keep these steps together since they are related.
Part of #https://github.com/pulumi/platform-providers-team/issues/44

Move change check to prerequisites

---

CHANGELOG.md
provider/pkg/provider/provider.go

The provider incorrectly assigned a time.Time struct to a string field. This worked for TypeScript, but resulted in an error in the other SDKs.

Convert token expiry to string on assignment

---

CHANGELOG.md
provider/pkg/provider/provider.go

GKE clusters have automated operations that can prevent API operations from succeeding. These API operations should be automatically retried since the cluster operation will eventually complete. This change adds a targeted retry in the provider that will be generalized in a later release.
Fix #434

fix: Retry GKE cluster operations

---

CHANGELOG.md
provider/pkg/gen/overrides.go
provider/pkg/gen/schema.go

Reverts #515 since that may cause issues with optional fieldmasks. Instead just add an override for `iam:v1/ServiceAccount` instead which actually is a required fieldmask.
Fixes #514

Add field-mask support for iam:v1/ServiceAccount

---

CHANGELOG.md
provider/pkg/provider/container.go
provider/pkg/provider/overrides.go
provider/pkg/provider/provider.go

Follow up from #588. 
This change marks all fields which are not covered by the explicit mutations in the custom nodepool implementation to cause replacements. We may push this down to the schema in the future.

Mark immutable fields for nodepools as replacements in diff

---

CHANGELOG.md
provider/pkg/provider/container.go
provider/pkg/provider/overrides.go
provider/pkg/provider/provider.go

Follow up from #588 
Since we need to split up multiple updates to satisfy the container/v1 api, in the event of partial success/failure (e.g. 2/3 updates succeed, last one fails), we want to record the inputs in the partial error checkpoint to reflect the successful portions but exclude the unsuccessful bits so they can be retried. Without this, pulumi assumes the entire batch of changes was successful.

Ensure inputs in partial error checkpoints for nodepools are correctly resumable

---

provider/pkg/provider/ids.go
provider/pkg/provider/ids_test.go
provider/pkg/provider/provider.go

This is the new system for deterministic names with update plans. The engine will fill in the random seed with a non-deterministic slice of bytes for normal updates, but when using plans it will save and restore the bytes used thus allowing names to be deterministic between preview and update. NewUniqueName handles the case of old engines that didn't send anything for seed by just falling back to non-deterministic randomness.

Use NewUniqueName

---

examples/iam-serviceaccount-ts/step1/index.ts
examples/iam-serviceaccount-ts/step1/package.json
examples/iam-serviceaccount-ts/step2/index.ts

service account doesn't currently support autonaming. Making the test create random names so we avoid potential conflicts.

chore: Fix iam-serviceaccount-ts test

---

CHANGELOG.md
provider/pkg/gen/overrides.go
provider/pkg/provider/provider.go

Exclude vpcaccess/v1:Connector from autonaming. Also fixes a panic during partial success checkpointing.
Fixes #358

Disable autonaming for vpcaccess/v1:Connector

---

CHANGELOG.md
examples/examples_nodejs_test.go
examples/gke-ts/step2/index.ts
provider/pkg/gen/overrides.go
provider/pkg/provider/container.go
provider/pkg/provider/diff.go
provider/pkg/provider/overrides.go
provider/pkg/provider/provider.go
provider/pkg/resources/resources.go

Extension of #588 to cluster.
Also extends the custom mutation support originally targeting v1 nodepools to include v1beta1 as well.
Fixes #124

Custom mutations for v1/v1beta1 cluster and nodepool

---

Makefile
provider/pkg/googleclient/credentials.go

Include a link to the registry installation-configuration guide, and improve readability by separating our message from the upstream error.
Error before:
Error after:
This PR also adds a convenience 'make install' and fixes the 'make install_nodejs_sdk', bringing both to be aligned with the pulumi-kubernetes Makefile.  If either of these changes is not desirable please let me know and I will adjust as needed.
Resolves #564

Improve failed auth error message

---

.github/workflows/build.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml
CHANGELOG.md
examples/examples_py_test.go
examples/kubeconfig-py/.gitignore
examples/kubeconfig-py/Pulumi.yaml
examples/kubeconfig-py/__main__.py
examples/kubeconfig-py/requirements.txt
provider/pkg/gen/schema.go
provider/pkg/provider/container.go
provider/pkg/provider/provider.go
sdk/dotnet/Container/V1/Cluster.cs
sdk/dotnet/Container/V1Beta1/Cluster.cs
sdk/go/google/container/v1/cluster.go
sdk/go/google/container/v1beta1/cluster.go
sdk/nodejs/container/v1/cluster.ts
sdk/nodejs/container/v1beta1/cluster.ts
sdk/python/pulumi_google_native/container/v1/cluster.py
sdk/python/pulumi_google_native/container/v1beta1/cluster.py

Fixes #635 
This change also addresses switching to `gke-gcloud-auth-plugin` for authentication as required by [Google](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke).

Add resource method for retrieving kubeconfig from a GKE cluster

---

provider/pkg/provider/provider.go

fixes #664
fixes #666
I welcome feedback on this approach, assigning env vars for config values if none have been configured via provider.  I removed the error if no project is designated, as that is not a requirement and it can be specified at the resource level.
related #565
I will address the docs issue in a registry PR.

Enable env vars for project, region, zone

---

provider/pkg/gen/overrides.go
provider/pkg/provider/provider.go

Fixes #689 
In addition, we no longer need to be skeptical about the response embedded in operation response since we do a fresh `GET` during creation and updates anyway.

Disable autonaming for tagkey/tagval

---

CHANGELOG.md
provider/pkg/provider/iam.go

The `getIamPolicy` endpoints are inconsistent across resources, and some include the `optionsRequestedPolicyVersion` query parameter. The version must be set to `3` to use IAM Conditions, so this parameter needs to be set on the endpoints that support it. Unfortunately, we can't include this parameter unconditionally because the request fails validation on the server for APIs that don't include it.

Fix Conditions handling for IAM policy updates

---

provider/pkg/gen/discovery.go
provider/pkg/gen/overrides.go
provider/pkg/gen/schema.go
provider/pkg/gen/schema_test.go
provider/pkg/gen/utilities.go
provider/pkg/provider/container.go
provider/pkg/provider/provider.go
provider/pkg/resources/resources.go
provider/pkg/resources/resources_test.go

Fixes #659
DNS managed zones and a few other resources need additional information for resolving the operations URL for updates etc than is readily available from the PATCH/Update response. Switching to an embedded endpoint gives us more control over resolving parameters where we can inject parameter values from the resource state or inputs.
The order of resolving URL params is:
1. Response payload from the relevant resource CRUD operation
2. Resource inputs
3. Resource outputs

Embed endpoints in operations instead of bespoke URL template processing

---

CHANGELOG.md
provider/pkg/provider/diff.go
provider/pkg/provider/diff_test.go

Resolves #909 
As per the resource property lookup grammar, certain fields need to be serialized in square brackets. 
https://github.com/pulumi/pulumi/blob/v3.75.0/sdk/go/common/resource/properties_path.go#L44

fix: resource paths can diff fields with dots

---

.github/workflows/build.yml
.github/workflows/run-acceptance-tests.yml
.gitignore
Makefile
codecov.yml

Modifies `make test_provider` to collect coverage profile files and adds a ci action to push them to codecov.
An example of the codecov analysis can be see in the comment below and at https://app.codecov.io/gh/pulumi/pulumi-google-native/commit/e2e535ad17dd7eee6a5509a3495a0a6dad2ca7b3

Add codecov to this repo

---

CHANGELOG.md
provider/pkg/gen/overrides.go

- Same issue as #209 which was fixed in #646

fix: Disable autonaming for iam/v1:OrganizationRole

---

.github/actions/install/action.yml
provider/go.mod

Unblock https://github.com/pulumi/pulumi-google-native/actions/runs/7030180233/job/19129224137

Update Go to 1.21, Go and .NET versions in CI

---

.github/workflows/weekly-pulumi-update.yml

`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

ci: Use GITHUB_OUTPUT envvar instead of set-output command
